trun: be more explicit when ncc0 or a.out crashes
Known (accepted) crashes have most of their output silenced, but we
still get the "Abort ..." message from bash. But it isn't clear which
test produced it. So we now print a non-suppressed message about such
crashes to make it easier to understand the origin of the bash message.

diff --git a/trun b/trun
--- a/trun
+++ b/trun
@@ -18,8 +18,9 @@ list=$(echo $list |perl -pe 's/\S*?\W?skipped_\S+//g')
 ret=0
 
 function build_and_run() {
-	$wd/ncc0 $1 2> $1.o.stderr || return
-	./a.out > $1.o.stdout 2>> $1.o.stderr || return
+	ret=0
+	$wd/ncc0 $1 2> $1.o.stderr || { ret=$?; report_crashes_only $1 "ncc0"; return; }
+	./a.out > $1.o.stdout 2>> $1.o.stderr || { ret=$?; report_crashes_only $1 "a.out"; return; }
 }
 
 function pretty_status() {
@@ -32,11 +33,18 @@ function pretty_status() {
 	fi
 }
 
+function report_crashes_only() {
+	t=$1
+	what=$2
+	if (( $ret > 128 )); then
+		echo "$what failed ($(pretty_status $ret)): $t"
+	fi
+}
+
 for t in $list; do
 	rm -f $t.o.{stderr,stdout,status}
 	if [ -f $t.ref.status ]; then
 		build_and_run $t
-		ret=$?
 		if (( $ret == 0 )); then
 			if cmp $t.o.stderr $t.ref.stderr && test -s $t.o.stderr; then
 				echo "FAILED $t: did not fail" \
@@ -47,7 +55,6 @@ for t in $list; do
 		fi
 	else
 		build_and_run $t
-		ret=$?
 		if (( $ret != 0 )); then
 			echo $ret > $t.o.status
 			echo "FAILED $t: did not succeed ($(pretty_status $ret))"
