trun: exiting with 0 while producing the expected non-empty stderr is a pass
With this change, we avoid a spurious
	FAILED t00/fixme05.n: did not fail (exit 0)
for tests that produce a stderr but do not exit with non-zero (e.g.
by writing non-fatal warnings to stderr).

We take the risk, however, that we will fail to detect tests that stop
returning non-zero exit code while producing the same stderr output.

We should really record the exit code too.

diff --git a/trun b/trun
--- a/trun
+++ b/trun
@@ -37,10 +37,16 @@ for t in $list; do
 		build_and_run $t
 		ret=$?
 		if (( $ret == 0 )); then
-			echo "FAILED $t: did not fail ($(pretty_status $ret))"
-			if ! [ -s $t.o.stderr ]; then
-				# Remove empty.
-				rm $t.o.stderr
+			if cmp $t.o.stderr $t.ref.stderr && test -s $t.o.stderr; then
+				# Exit code is 0, but stderr is not empty and
+				# matches the reference. That's a success.
+				echo -n
+			else
+				echo "FAILED $t: did not fail ($(pretty_status $ret))"
+				if ! [ -s $t.o.stderr ]; then
+					# Remove empty.
+					rm $t.o.stderr
+				fi
 			fi
 		fi
 	else
